// import EChartsBar from '_c/echarts/bar.vue'
// import EChartsPie from '_c/echarts/pie.vue'
// import EChartsLine from '_c/echarts/line.vue'
// import EChartsMap from '_c/echarts/map.vue'
import Icon from '_c/icon'
import Table from '_c/table'
// import Loading from '_c/loading'
// import Main from '_c/main'
import LoadingBar from '_c/loading-bar'
import Switch from '_c/switch'
import { Dialog } from '_c/dialog'
// import quillEditor from '_c/quill'
import uploadBar from '_c/upload-bar'
import BindGoogleAuth from './bind-google-auth'

export { Icon, Table, LoadingBar, Switch, Dialog, uploadBar, BindGoogleAuth }
